<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>QuickSheetDepr</RootNamespace>
    <AssemblyName>QuickSheetDepr</AssemblyName>
  </PropertyGroup>
</Project>
